[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "template-package"
version = "0.1.0"
description = "Template package - SHOULD BE EXCLUDED from Dependabot monitoring"
dependencies = [
    # These dependencies should NOT appear in Dependabot monitoring
    "jinja2>=3.1.0",
    "cookiecutter>=2.1.0",
    "pyyaml>=6.0.0",
    "click>=8.1.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "coverage>=7.0.0",
]

# This file is in backend/packages/template/ and should be excluded
