[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "app1-package"
version = "0.1.0"
description = "App1 package - should be monitored by Dependabot"
dependencies = [
    "django>=4.2.0",
    "django-rest-framework>=3.14.0",
    "celery>=5.2.0",
    "redis>=4.5.0",
]

[project.optional-dependencies]
dev = [
    "pytest-django>=4.5.0",
    "factory-boy>=3.2.0",
]
