[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "app2-package"
version = "0.1.0"
description = "App2 package - should be monitored by Dependabot"
dependencies = [
    "flask>=2.3.0",
    "flask-sqlalchemy>=3.0.0",
    "marshmallow>=3.19.0",
    "gunicorn>=20.1.0",
]

[project.optional-dependencies]
dev = [
    "pytest-flask>=1.2.0",
    "flask-testing>=0.8.0",
]
